spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(bGvDWXdgAsFNCvvwrW9+eQ==)
    password: ENC(yb9c5bnqFBYAoXvuBddv6A==)
    url: ENC(m2u1QauptRPYaavOyEZltvqll4OT8FlsqNnylbGBtdRvFn78/MOFGvuck7byK/GMMYp05vrKyspMUo7/WkooskZv9wvXkckLi69LZTnz/NpsOvWyvYu1Nm3evyEXXyorzyAjeWphckQ=)

  mvc:
    path match:
      matching-strategy: ant_path_matcher

jasypt:
  key: ${JASYPT_KEY}
